[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build]
exclude = [
  "/dist",
  "/notebooks",
  "/scripts",
  "/bin",
  "/tests",
]

[tool.hatch.build.targets.wheel]
packages = ["src/scaleagdata_vito"]

[tool.hatch.version]
path = "src/scaleagdata_vito/_version.py"
pattern = "^__version__ = ['\"](?P<version>[^'\"]+)['\"]$"

[tool.hatch.metadata]
allow-direct-references = true

[project]
name = "scaleag-vito"
authors = [
  { name="Giorgia Milli" },
  { name="Kristof Van Tricht" },
  { name="Christina Butsko" },
]
description = "using Presto for few-shot learning downstream tasks"
readme = "README.md"
requires-python = ">=3.10"
dynamic = ["version"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "cftime",
    "geojson",
    "geopandas",
    "h3~=4.1.0",
    "h5netcdf>=1.3.0",
    "loguru>=0.7.2",
    "netcdf4>=1.6.4",
    "numpy>=2.4.0",
    "openeo>=0.47.0",
    "openeo-gfmap @ git+https://github.com/Open-EO/openeo-gfmap.git@maintenance/0.4.x",
    "prometheo @ git+https://github.com/WorldCereal/prometheo.git@v0.0.4",
    "pyarrow",
    "pytest-depends",
    "rioxarray>=0.13.0",
    "scikit-image",
    "scipy",
    "tabulate>=0.9.0",
    "xarray>=2022.3.0",
  ]

[project.urls]
"Homepage" = "https://github.com/ScaleAGData/scaleag-vito"
"Bug Tracker" = "https://github.com/ScaleAGData/scaleag-vito/issues"

[project.optional-dependencies]
dev = [
  "pytest>=7.4.0",
  "pytest-depends", 
  "matplotlib>=3.3.0",
]

notebooks = [
  "ipywidgets~=8.1.3",
  "ipyleaflet>=0.19.0",
  "leafmap==0.35.1"
]

train = [
  "catboost~=1.2.8",
  "matplotlib>=3.3.0",
  "scikit-learn",
  "torch>=2.3.0",
  "pystac==1.10.1",
  "pystac-client==0.8.3",
  "seaborn"
]

[tool.pytest.ini_options]
testpaths = [
  "tests",
]
addopts = [
  "--import-mode=prepend",
]

[tool.ruff]
exclude = ["**/*.ipynb"]
lint.extend-select = ["E", "F", "I"]
lint.ignore = [
  "E501"
]